version: "3"
services:
  server:
    build: .
    ports:
      - "8083:8083"
    container_name: qcs-server

  db:
    container_name: qcs-db
    image: 'postgres:14'
    ports:
      - "15432:5432"
    environment:
      # TODO: change these values according to project
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=db_user
      - POSTGRES_DB=qcs_db

  redis:
    container_name: qcs-redis
    image: docker.io/bitnami/redis:7.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
