spring:
  datasource:
    dynamic:
      hikari:
        min-idle: 10
        max-pool-size: 10
        connection-timeout: 30000
      primary: postgres
      p6spy: false
      datasource:
        postgres:
          type: com.zaxxer.hikari.HikariDataSource
          driverClassName: org.postgresql.Driver
          url: jdbc:postgresql://10.2.3.115:5433/centralkitchen
          username: manager
          password: ENC(o7iuJ58LoA1okptjlVxt4w==)
        sqlserver:
          type: com.zaxxer.hikari.HikariDataSource
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://192.168.1.129:1433; DatabaseName=dbOrder;
          username: freshorder
          password: ENC(qkQM02liXxNveGLsOfesyg==)
  mail:
    host: cn.tre-inc.com
    username: xxxxxxxxx@cn.tre-inc.com
    password: ENC(TN9p6M/bT0dCB2XaLsVgcQ==)
    default-encoding: UTF-8
    protocol: smtp

  redis:
    host: xxx.xxx.xxx.xxx
    port: 6379
    database: 0
    password:
    timeout: 1000
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100

logging:
  config: classpath:logback-spring-product.xml

login:
  url: https://auth.trial-net.co.jp/Apps/authentication/authenticate
  key: 17584422-f360-40ef-9832-7571e5118b4e

menu:
  masterAuthority: 13
  userAuthority: 16

LinkSubIp:
  ip20: 10.2.12.20
  ip120: 10.2.3.120

print:
  print-url: http://10.2.4.86/PrintCommonAPI/PrintCenterService/getPrintCenter?
  print-file-url: http://10.2.3.112:10803/ck/api/file/download/

